runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: assets/favicon.ico
  upload: assets/favicon\.ico

- url: .*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
